version: 1

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
