# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: null

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: maximize
    n_trials: 10

    sampler:
      _target_: optuna.samplers.RandomSampler

    params:
      data.batch_size: choice(32, 64, 128, 256)
      module.lr_scheduler.max_lr: interval(0.001, 1)
      module.optimizer.momentum: interval(0.1, 0.9)
