# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: null

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: maximize
    n_trials: 10

    sampler:
      _target_: optuna.samplers.RandomSampler

    search_space:
      data.batch_size:
        type: categorical
        choices: [32, 64, 128]
      module.optimizer.lr:
        type: categorical
        choices: [0.0001, 0.001, 0.01, 0.1]
      module.optimizer._target_:
        type: categorical
        choices: ["torch.optim.Adam", "adabelief_pytorch.AdaBelief"]
      module.loss.gamma:
        type: categorical
        choices: [1, 2, 3, 4]
