hyperparameters:
  lr: &lr 0.003

seed: 123

trainer:
  name: pytorch_lightning.Trainer
  kwargs:
    profiler: pytorch
    gpus: -1
    auto_select_gpus: true

callbacks:
  model_checkpoint:
    name: pytorch_lightning.callbacks.ModelCheckpoint
    kwargs:
      save_top_k: 3
      monitor: "val_loss"
      save_weights_only: False
      mode: min
      every_n_epochs: 1

  lr_monitor:
    name: pytorch_lightning.callbacks.LearningRateMonitor
    kwargs:
      logging_interval: "step"
      log_momentum: true

training_logger:
  name: pytorch_lightning.loggers.TensorBoardLogger
  kwargs:
    save_dir: "."
    name: lightning_logs
    default_hp_metric: false
    log_graph: true

module:
  network:
    name: image_classification.network.MNISTNet
  loss:
    name: torch.nn.CrossEntropyLoss
  optimizer:
    name: torch.optim.Adam
    kwargs:
      lr: *lr
  lr_scheduler:
    name: torch.optim.lr_scheduler.ReduceLROnPlateau
    monitor: "val_loss"

data:
  name: image_classification.data.MNISTDataModule
  kwargs:
    data_dir: ./data
    download: true
