# @package _global_

seed: 7

trainer:
  _target_: pytorch_lightning.Trainer
  profiler: "pytorch"
  max_epochs: 30
  gpus: -1
  auto_select_gpus: true

training_logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: "."
  name: ""
  version: tensorboard
  default_hp_metric: True
  log_graph: true

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 3
    monitor: "val_loss"
    save_weights_only: False
    mode: min
    every_n_epochs: 1

  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
    log_momentum: true
